### PR TITLE
*updated* Redesign Beginning 

### PR DESCRIPTION
**Pull request by michaeldeborst**
So this is a quick beginning I put together. Let me know what you guys think.
I would advise to create a new branch in the repo for the redesign and when it's done we can push it through to master.

### CODE REVIEW

**Comment by kingosticks** [comment]
How does this sass stuff work? Can we still just push changes to github and see the updated site or is there now a build step that's required?

**Comment by michaeldeborst** [comment]
No it doesn't need to be built. TBH I doubt it's even really necesary. I'll see if I can get rid of it.

**EDIT** the Sass stuff isn't required and can be removed. I wrote some of it for a CMS project I was working on but this won't be necessary for this project

**Comment by kingosticks** [comment]
First up just want to say thanks very much for taking the time, it's great to have contributions. I have some initial thoughts:

* I really like that elegant logo! I've toyed with all sorts of ideas trying to incorporate boxes, musical notation, pi symbols, python symbols.... there is something to be said for simple.
* The style in general is a little corporate and I'm not sure that quite fits with the project. Do you know what I mean? 
* Would quite like to keep the musicbox-webclient colour(s), not sure if it's deliberately a different shade. Perhaps we could try and get one of the raspberry pi logo colours in there, or maybe in the logo.
* I'm personally not a fan of transitions, reminds me of power point
* I think just right-aligned text links at the top rather than the menu

Is there anything to be gained with opening a branch here versus using yours?

**Comment by michaeldeborst** [comment]
I was certainly going for clean in this case. I can make it a bit more playful and I agree with you on the color change. I'll also replace the menu. I personally really like the transitions. IMHO it makes the experience more straightforward. 

I'm not 100 % confident about the logo. It was just some toying around with some CSS libs I found and this came out. I like the result and definitely think it's a good placeholder. 

I don't know how picky you are in terms of allowing people write access to your repo's ( I totally understand you don't want some random people messing up your Git). Personally I prefer using branches in the same repo over using forks, since people visiting the main repo can also see the redesign branch. I'm fine either way though.

**Pull request merged**
